export const addressConstant = {

    REQUEST: 'REQUEST',
    SUCCESS_ADD_ADDRESS: 'SUCCESS_ADD_ADDRESS',
    SUCCESS_DELETE_ADDRESS: 'SUCCESS_DELETE_ADDRESS',
    SUCCESS_EDIT_ADDRESS: 'SUCCESS_EDIT_ADDRESS',
    FAIL: 'FAIL',
}