export const cartConstant = {

    REQUEST_CART: 'REQUEST_CART',
    GET_CART: 'GET_CART',
    ADD_PRODUCT: 'ADD_PRODUCT',
    SUCCESS_ADD: 'SUCCESS_ADD' ,
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    ADD_QUANTITY: 'ADD_QUANTITY',
    DROP_QUANTITY: 'DROP_QUANTITY',
    FAIL: 'FAIL'
}