
export const OrderConstant = {
    CHECKOUT: 'CHECKOUT',
    REQUEST_CREATE_ORDER: 'REQUEST_CREATE_ORDER',
    CREATE_ORDER: 'CREATE_ORDER'   ,
    FAIL: 'FAIL',
    REQUEST_ORDER_DETAIL: 'REQUEST_ORDER_DETAIL',
    SUCCESS_ORDER_DETAIL: 'SUCCESS_ORDER_DETAIL',
    GET_ALL_ORDER: 'GET_ALL_ORDER'

}