export const productDetail = {

    REQUEST_PRODUCT_DETAIL: 'REQUEST_PRODUCT_DETAIL',
    SUCCESS_REQUEST_PRODUCT: 'SUCCESS_REQUEST_PRODUCT',
    FAIL_REQUEST_PRODUCT: 'FAIL_REQUEST_PRODUCT',
    RESET: 'RESET',
}